#!/bin/bash
DEST="$HOME/backups/neolibrary"
SRC="neolibrary/static"
ONGDB_BIN="$HOME/Programs/ongdb-enterprise/bin"
NAME="neolibrary.backup"

rsync -rv --delete $SRC $DEST

mkdir -p "$DEST/neo4j"
"$ONGDB_BIN"/neo4j-admin backup --backup-dir="$DEST/neo4j" --name="$NAME"
